SAS/Models/Student_classProgram.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SAS.Models
{
    public class Student_classProgram
    {
        [Key]
        public int Student_Class_id { get; set; }
        [Required(ErrorMessage = "Student Name is required !")]
        [Display(Name = "Student Name")]
        public int Stud_id { get; set; }
        [ForeignKey("Stud_id")]
        public Student Student { get; set; }

        [Required(ErrorMessage = "Academic year is required !")]
        [Display(Name = "Academic year")]
        public int Academic_y_id { get; set; }
        [ForeignKey("Academic_y_id")]
        public Academic_Year Academic_Year { get; set; }


        [Required(ErrorMessage = "Class program is required !")]
        [Display(Name = "Class Program / Schedule")]
        public int ClassProgram_id { get; set; }
        [ForeignKey("ClassProgram_id")]
        public Class_program Class_program { get; set; }

        [Required(ErrorMessage = "Department Name is required !")]
        [Display(Name = "Department Name")]
        public int Department_id { get; set; }
        [ForeignKey("Department_id")]
        public Department Department { get; set; }

        [Required(ErrorMessage = "Faculity Name is required !")]
        [Display(Name = "Faculity Name")]
        public int Faculity_id { get; set; }
        [ForeignKey("Faculity_id")]
        public Faculity Faculity { get; set; }


        [Required(ErrorMessage = "Semester is required !")]
        [Display(Name = "Semester")]
        public int Semester_id { get; set; }
        [ForeignKey("Semester_id")]
        public Semester Semester { get; set; }

        [Required(ErrorMessage = "Status is required !")]
        [Display(Name = "Status")]
        public string Status { get; set; }


    }
}

SAS/Controllers/Student_classProgramController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SAS.Data;
using SAS.Models;

namespace SAS.Controllers
{
    public class Student_classProgramController : Controller
    {
        private readonly ApplicationDbContext _context;

        public Student_classProgramController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Student_classProgram
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Student_class.Include(s => s.Academic_Year).Include(s => s.Class_program).Include(s => s.Department).Include(s => s.Faculity).Include(s => s.Semester).Include(s => s.Student);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Student_classProgram/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Student_class == null)
            {
                return NotFound();
            }

            var student_classProgram = await _context.Student_class
                .Include(s => s.Academic_Year)
                .Include(s => s.Class_program)
                .Include(s => s.Department)
                .Include(s => s.Faculity)
                .Include(s => s.Semester)
                .Include(s => s.Student)
                .FirstOrDefaultAsync(m => m.Student_Class_id == id);
            if (student_classProgram == null)
            {
                return NotFound();
            }

            return View(student_classProgram);
        }

        // GET: Student_classProgram/Create
        public IActionResult Create()
        {
            ViewData["Academic_y_id"] = new SelectList(_context.Academic_Year, "Academic_y_id", "Academic_yearName");
            ViewData["ClassProgram_id"] = new SelectList(_context.Class_program, "ClassProgram_id", "ClassProgram_id");
            ViewData["Department_id"] = new SelectList(_context.Department, "Department_id", "Department_name");
            ViewData["Faculity_id"] = new SelectList(_context.Faculities, "Faculity_id", "Faculty_name");
            ViewData["Semester_id"] = new SelectList(_context.Semester, "Semester_id", "SemesterName");
            ViewData["Stud_id"] = new SelectList(_context.Student, "Stud_id", "FullName");
            return View();
        }

        // POST: Student_classProgram/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Student_Class_id,Stud_id,Academic_y_id,ClassProgram_id,Department_id,Faculity_id,Semester_id,Status")] Student_classProgram student_classProgram)
        {
            if (!ModelState.IsValid)
            {
                _context.Add(student_classProgram);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Academic_y_id"] = new SelectList(_context.Academic_Year, "Academic_y_id", "Academic_yearName", student_classProgram.Academic_y_id);
            ViewData["ClassProgram_id"] = new SelectList(_context.Class_program, "ClassProgram_id", "ClassProgram_id", student_classProgram.ClassProgram_id);
            ViewData["Department_id"] = new SelectList(_context.Department, "Department_id", "Department_name", student_classProgram.Department_id);
            ViewData["Faculity_id"] = new SelectList(_context.Faculities, "Faculity_id", "Faculty_name", student_classProgram.Faculity_id);
            ViewData["Semester_id"] = new SelectList(_context.Semester, "Semester_id", "SemesterName", student_classProgram.Semester_id);
            ViewData["Stud_id"] = new SelectList(_context.Student, "Stud_id", "FullName", student_classProgram.Stud_id);
            return View(student_classProgram);
        }

        // GET: Student_classProgram/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Student_class == null)
            {
                return NotFound();
            }

            var student_classProgram = await _context.Student_class.FindAsync(id);
            if (student_classProgram == null)
            {
                return NotFound();
            }
            ViewData["Academic_y_id"] = new SelectList(_context.Academic_Year, "Academic_y_id", "Academic_yearName", student_classProgram.Academic_y_id);
            ViewData["ClassProgram_id"] = new SelectList(_context.Class_program, "ClassProgram_id", "ClassProgram_id", student_classProgram.ClassProgram_id);
            ViewData["Department_id"] = new SelectList(_context.Department, "Department_id", "Department_name", student_classProgram.Department_id);
            ViewData["Faculity_id"] = new SelectList(_context.Faculities, "Faculity_id", "Faculty_name", student_classProgram.Faculity_id);
            ViewData["Semester_id"] = new SelectList(_context.Semester, "Semester_id", "SemesterName", student_classProgram.Semester_id);
            ViewData["Stud_id"] = new SelectList(_context.Student, "Stud_id", "FullName", student_classProgram.Stud_id);
            return View(student_classProgram);
        }

        // POST: Student_classProgram/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Student_Class_id,Stud_id,Academic_y_id,ClassProgram_id,Department_id,Faculity_id,Semester_id,Status")] Student_classProgram student_classProgram)
        {
            if (id != student_classProgram.Student_Class_id)
            {
                return NotFound();
            }

            if (!ModelState.IsValid)
            {
                try
                {
                    _context.Update(student_classProgram);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!Student_classProgramExists(student_classProgram.Student_Class_id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Academic_y_id"] = new SelectList(_context.Academic_Year, "Academic_y_id", "Academic_yearName", student_classProgram.Academic_y_id);
            ViewData["ClassProgram_id"] = new SelectList(_context.Class_program, "ClassProgram_id", "ClassProgram_id", student_classProgram.ClassProgram_id);
            ViewData["Department_id"] = new SelectList(_context.Department, "Department_id", "Department_name", student_classProgram.Department_id);
            ViewData["Faculity_id"] = new SelectList(_context.Faculities, "Faculity_id", "Faculty_name", student_classProgram.Faculity_id);
            ViewData["Semester_id"] = new SelectList(_context.Semester, "Semester_id", "SemesterName", student_classProgram.Semester_id);
            ViewData["Stud_id"] = new SelectList(_context.Student, "Stud_id", "FullName", student_classProgram.Stud_id);
            return View(student_classProgram);
        }

        // GET: Student_classProgram/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Student_class == null)
            {
                return NotFound();
            }

            var student_classProgram = await _context.Student_class
                .Include(s => s.Academic_Year)
                .Include(s => s.Class_program)
                .Include(s => s.Department)
                .Include(s => s.Faculity)
                .Include(s => s.Semester)
                .Include(s => s.Student)
                .FirstOrDefaultAsync(m => m.Student_Class_id == id);
            if (student_classProgram == null)
            {
                return NotFound();
            }

            return View(student_classProgram);
        }

        // POST: Student_classProgram/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Student_class == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Student_class'  is null.");
            }
            var student_classProgram = await _context.Student_class.FindAsync(id);
            if (student_classProgram != null)
            {
                _context.Student_class.Remove(student_classProgram);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool Student_classProgramExists(int id)
        {
          return (_context.Student_class?.Any(e => e.Student_Class_id == id)).GetValueOrDefault();
        }
    }
}

SAS/Views/Student_classProgram/Create.cshtml
@model SAS.Models.Student_classProgram

@{
    ViewData["Title"] = "Create";
}

<div class="content-header" style="padding-left:250px; color:black;padding-bottom: 40px;padding-top: 10px;">
</div>

<div class="mainbody" style="padding-left:250px;">
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Stud_id" class="control-label"></label>
                <select asp-for="Stud_id" class ="form-control" asp-items="ViewBag.Stud_id"></select>
            </div>
            <div class="form-group">
                <label asp-for="Academic_y_id" class="control-label"></label>
                <select asp-for="Academic_y_id" class ="form-control" asp-items="ViewBag.Academic_y_id"></select>
            </div>
            <div class="form-group">
                <label asp-for="ClassProgram_id" class="control-label"></label>
                <select asp-for="ClassProgram_id" class ="form-control" asp-items="ViewBag.ClassProgram_id"></select>
            </div>
            <div class="form-group">
                <label asp-for="Department_id" class="control-label"></label>
                <select asp-for="Department_id" class ="form-control" asp-items="ViewBag.Department_id"></select>
            </div>
            <div class="form-group">
                <label asp-for="Faculity_id" class="control-label"></label>
                <select asp-for="Faculity_id" class ="form-control" asp-items="ViewBag.Faculity_id"></select>
            </div>
            <div class="form-group">
                <label asp-for="Semester_id" class="control-label"></label>
                <select asp-for="Semester_id" class ="form-control" asp-items="ViewBag.Semester_id"></select>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <input asp-for="Status" class="form-control" />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
                    <a asp-action="Index">Back to List</a>
            </div>
        </form>
    </div>
</div>
  
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SAS/Views/Student_classProgram/Delete.cshtml
@model SAS.Models.Student_classProgram

@{
    ViewData["Title"] = "Delete";
}
<div class="content-header" style="padding-left:250px; color:black;padding-bottom: 40px;padding-top: 10px;">
    <h3>Are you sure you want to delete this?</h3>
</div>

<div class="mainbody" style="padding-left:250px;">
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Student)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Student.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Academic_Year)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Academic_Year.Academic_yearName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Class_program)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Class_program.ClassProgram_id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Department)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Department.Department_code)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Faculity)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Faculity.Faculty_email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Semester)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Semester.SemesterName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
    </dl>

    <div class="form-group">
        <form asp-action="Delete">
            <input type="hidden" asp-for="Student_Class_id" />
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            <a asp-action="Index">Back to List</a>
        </form>
    </div>
</div>





    

SAS/Views/Student_classProgram/Details.cshtml
@model SAS.Models.Student_classProgram

@{
    ViewData["Title"] = "Details";
}

<div class="content-header" style="padding-left:250px; color:black;padding-bottom: 40px;padding-top: 10px;">
</div>

<div class="mainbody" style="padding-left:250px;">
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Student)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Student.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Academic_Year)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Academic_Year.Academic_yearName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Class_program)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Class_program.ClassProgram_id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Department)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Department.Department_code)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Faculity)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Faculity.Faculty_email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Semester)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Semester.SemesterName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Student_Class_id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>


   

SAS/Views/Student_classProgram/Edit.cshtml
@model SAS.Models.Student_classProgram

@{
    ViewData["Title"] = "Edit";
}
<div class="content-header" style="padding-left:250px; color:black;padding-bottom: 40px;padding-top: 10px;">
</div>

<div class="mainbody" style="padding-left:250px;">
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Student_Class_id" />
            <div class="form-group">
                <label asp-for="Stud_id" class="control-label"></label>
                <select asp-for="Stud_id" class="form-control" asp-items="ViewBag.Stud_id"></select>
                <span asp-validation-for="Stud_id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Academic_y_id" class="control-label"></label>
                <select asp-for="Academic_y_id" class="form-control" asp-items="ViewBag.Academic_y_id"></select>
                <span asp-validation-for="Academic_y_id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ClassProgram_id" class="control-label"></label>
                <select asp-for="ClassProgram_id" class="form-control" asp-items="ViewBag.ClassProgram_id"></select>
                <span asp-validation-for="ClassProgram_id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Department_id" class="control-label"></label>
                <select asp-for="Department_id" class="form-control" asp-items="ViewBag.Department_id"></select>
                <span asp-validation-for="Department_id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Faculity_id" class="control-label"></label>
                <select asp-for="Faculity_id" class="form-control" asp-items="ViewBag.Faculity_id"></select>
                <span asp-validation-for="Faculity_id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Semester_id" class="control-label"></label>
                <select asp-for="Semester_id" class="form-control" asp-items="ViewBag.Semester_id"></select>
                <span asp-validation-for="Semester_id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <input asp-for="Status" class="form-control" />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
                    <a asp-action="Index">Back to List</a>
            </div>
        </form>
    </div>
</div>
   
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SAS/Views/Student_classProgram/Index.cshtml
@model IEnumerable<SAS.Models.Student_classProgram>

@{
    ViewData["Title"] = "Index";
}
<div class="content-header" style="padding-left:250px; color:black;padding-bottom: 40px;padding-top: 10px;">
    <a asp-action="Create" asp-controller="Student_classProgram" class="btn btn-primary" style="float:right;"> Add New  </a>
</div>

<div class="mainbody" style="padding-left:250px;">
    <table id="example" class="display" style="width:100%">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Student)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Academic_Year)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Class_program)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Department)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Faculity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Semester)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                    @Html.DisplayFor(modelItem => item.Student.FullName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Academic_Year.Academic_yearName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Class_program.ClassProgram_id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Department.Department_name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Faculity.Faculty_name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Semester.SemesterName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Student_Class_id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Student_Class_id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Student_Class_id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>
</div>