SAS/Models/Course_teacher.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SAS.Models
{
    public class Course_teacher
    {
        [Key]
        public int Course_teacher_id { get; set; }

        [Required(ErrorMessage = "Teacher Name is required !")]
        [Display(Name = "Teacher Name")]
        public int Teacher_id { get; set; }
        [ForeignKey("Teacher_id")]
        public Teacher Teacher { get; set; }

        [Required(ErrorMessage = "Academic year is required !")]
        [Display(Name = "Academic Year")]
        public int Academic_y_id { get; set; }
        [ForeignKey("Academic_y_id")]
        public Academic_Year Academic_Year { get; set; }

        [Required(ErrorMessage = "Semester is required !")]
        [Display(Name = "Semester")]
        public int Semester_id { get; set; }
        [ForeignKey("Semester_id")]
        public Semester Semester { get; set; }

        [Required(ErrorMessage = "Faculity Name is required !")]
        [Display(Name = "Faculity Name")]
        public int Faculity_id { get; set; }
        [ForeignKey("Faculity_id")]
        public Faculity Faculity { get; set; }

        [Required(ErrorMessage = "Department Name is required !")]
        [Display(Name = "Department Name")]
        public int Department_id { get; set; }
        [ForeignKey("Department_id")]
        public Department Department { get; set; }

        [Required(ErrorMessage = "Course Name is required !")]
        [Display(Name = "Course Name")]
        public int Course_id { get; set; }
        [ForeignKey("Course_id")]
        public Course Course { get; set; }

        [Required(ErrorMessage = "Status is required !")]
        [Display(Name = "Status")]
        public String Status { get; set; }



    }
}

SAS/Controllers/Course_teacherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SAS.Data;
using SAS.Models;

namespace SAS.Controllers
{
    public class Course_teacherController : Controller
    {
        private readonly ApplicationDbContext _context;

        public Course_teacherController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Course_teacher
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Course_teacher.Include(c => c.Academic_Year).Include(c => c.Course).Include(c => c.Department).Include(c => c.Faculity).Include(c => c.Semester).Include(c => c.Teacher);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Course_teacher/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Course_teacher == null)
            {
                return NotFound();
            }

            var course_teacher = await _context.Course_teacher
                .Include(c => c.Academic_Year)
                .Include(c => c.Course)
                .Include(c => c.Department)
                .Include(c => c.Faculity)
                .Include(c => c.Semester)
                .Include(c => c.Teacher)
                .FirstOrDefaultAsync(m => m.Course_teacher_id == id);
            if (course_teacher == null)
            {
                return NotFound();
            }

            return View(course_teacher);
        }

        // GET: Course_teacher/Create
        public IActionResult Create()
        {
            ViewData["Academic_y_id"] = new SelectList(_context.Academic_Year, "Academic_y_id", "Academic_yearName");
            ViewData["Course_id"] = new SelectList(_context.Course, "Course_id", "Course_name");
            ViewData["Department_id"] = new SelectList(_context.Department, "Department_id", "Department_name");
            ViewData["Faculity_id"] = new SelectList(_context.Faculities, "Faculity_id", "Faculty_name");
            ViewData["Semester_id"] = new SelectList(_context.Semester, "Semester_id", "SemesterName");
            ViewData["Teacher_id"] = new SelectList(_context.Teacher, "Teacher_id", "FullNameOfTeacher");
            return View();
        }

        // POST: Course_teacher/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Course_teacher_id,Teacher_id,Academic_y_id,Semester_id,Faculity_id,Department_id,Course_id,Status")] Course_teacher course_teacher)
        {
            if (!ModelState.IsValid)
            {
                _context.Add(course_teacher);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Academic_y_id"] = new SelectList(_context.Academic_Year, "Academic_y_id", "Academic_yearName", course_teacher.Academic_y_id);
            ViewData["Course_id"] = new SelectList(_context.Course, "Course_id", "Course_name", course_teacher.Course_id);
            ViewData["Department_id"] = new SelectList(_context.Department, "Department_id", "Department_name", course_teacher.Department_id);
            ViewData["Faculity_id"] = new SelectList(_context.Faculities, "Faculity_id", "Faculty_name", course_teacher.Faculity_id);
            ViewData["Semester_id"] = new SelectList(_context.Semester, "Semester_id", "SemesterName", course_teacher.Semester_id);
            ViewData["Teacher_id"] = new SelectList(_context.Teacher, "Teacher_id", "FullNameOfTeacher", course_teacher.Teacher_id);
            return View(course_teacher);
        }

        // GET: Course_teacher/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Course_teacher == null)
            {
                return NotFound();
            }

            var course_teacher = await _context.Course_teacher.FindAsync(id);
            if (course_teacher == null)
            {
                return NotFound();
            }
            ViewData["Academic_y_id"] = new SelectList(_context.Academic_Year, "Academic_y_id", "Academic_yearName", course_teacher.Academic_y_id);
            ViewData["Course_id"] = new SelectList(_context.Course, "Course_id", "Course_name", course_teacher.Course_id);
            ViewData["Department_id"] = new SelectList(_context.Department, "Department_id", "Department_name", course_teacher.Department_id);
            ViewData["Faculity_id"] = new SelectList(_context.Faculities, "Faculity_id", "Faculty_name", course_teacher.Faculity_id);
            ViewData["Semester_id"] = new SelectList(_context.Semester, "Semester_id", "SemesterName", course_teacher.Semester_id);
            ViewData["Teacher_id"] = new SelectList(_context.Teacher, "Teacher_id", "FullNameOfTeacher", course_teacher.Teacher_id);
            return View(course_teacher);
        }

        // POST: Course_teacher/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Course_teacher_id,Teacher_id,Academic_y_id,Semester_id,Faculity_id,Department_id,Course_id,Status")] Course_teacher course_teacher)
        {
            if (id != course_teacher.Course_teacher_id)
            {
                return NotFound();
            }

            if (!ModelState.IsValid)
            {
                try
                {
                    _context.Update(course_teacher);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!Course_teacherExists(course_teacher.Course_teacher_id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Academic_y_id"] = new SelectList(_context.Academic_Year, "Academic_y_id", "Academic_yearName", course_teacher.Academic_y_id);
            ViewData["Course_id"] = new SelectList(_context.Course, "Course_id", "Course_name", course_teacher.Course_id);
            ViewData["Department_id"] = new SelectList(_context.Department, "Department_id", "Department_name", course_teacher.Department_id);
            ViewData["Faculity_id"] = new SelectList(_context.Faculities, "Faculity_id", "Faculty_name", course_teacher.Faculity_id);
            ViewData["Semester_id"] = new SelectList(_context.Semester, "Semester_id", "SemesterName", course_teacher.Semester_id);
            ViewData["Teacher_id"] = new SelectList(_context.Teacher, "Teacher_id", "FullNameOfTeacher", course_teacher.Teacher_id);
            return View(course_teacher);
        }

        // GET: Course_teacher/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Course_teacher == null)
            {
                return NotFound();
            }

            var course_teacher = await _context.Course_teacher
                .Include(c => c.Academic_Year)
                .Include(c => c.Course)
                .Include(c => c.Department)
                .Include(c => c.Faculity)
                .Include(c => c.Semester)
                .Include(c => c.Teacher)
                .FirstOrDefaultAsync(m => m.Course_teacher_id == id);
            if (course_teacher == null)
            {
                return NotFound();
            }

            return View(course_teacher);
        }

        // POST: Course_teacher/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Course_teacher == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Course_teacher'  is null.");
            }
            var course_teacher = await _context.Course_teacher.FindAsync(id);
            if (course_teacher != null)
            {
                _context.Course_teacher.Remove(course_teacher);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool Course_teacherExists(int id)
        {
          return (_context.Course_teacher?.Any(e => e.Course_teacher_id == id)).GetValueOrDefault();
        }
    }
}

SAS/Views/Course_teacher/Create.cshtml
@model SAS.Models.Course_teacher

@{
    ViewData["Title"] = "Create";
}

<div class="content-header" style="padding-left:250px; color:black;padding-bottom: 40px;padding-top: 10px;">
</div>

<div class="mainbody" style="padding-left:250px;">
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Teacher_id" class="control-label"></label>
                <select asp-for="Teacher_id" class ="form-control" asp-items="ViewBag.Teacher_id"></select>
            </div>
            <div class="form-group">
                <label asp-for="Academic_y_id" class="control-label"></label>
                <select asp-for="Academic_y_id" class ="form-control" asp-items="ViewBag.Academic_y_id"></select>
            </div>
            <div class="form-group">
                <label asp-for="Semester_id" class="control-label"></label>
                <select asp-for="Semester_id" class ="form-control" asp-items="ViewBag.Semester_id"></select>
            </div>
            <div class="form-group">
                <label asp-for="Faculity_id" class="control-label"></label>
                <select asp-for="Faculity_id" class ="form-control" asp-items="ViewBag.Faculity_id"></select>
            </div>
            <div class="form-group">
                <label asp-for="Department_id" class="control-label"></label>
                <select asp-for="Department_id" class ="form-control" asp-items="ViewBag.Department_id"></select>
            </div>
            <div class="form-group">
                <label asp-for="Course_id" class="control-label"></label>
                <select asp-for="Course_id" class ="form-control" asp-items="ViewBag.Course_id"></select>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <input asp-for="Status" class="form-control" />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
                    <a asp-action="Index">Back to List</a>
            </div>
        </form>
    </div>
</div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SAS/Views/Course_teacher/Delete.cshtml
@model SAS.Models.Course_teacher

@{
    ViewData["Title"] = "Delete";
}

<div class="content-header" style="padding-left:250px; color:black;padding-bottom: 40px;padding-top: 10px;">
    <h3>Are you sure you want to delete this?</h3>
</div>

<div class="mainbody" style="padding-left:250px;">
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Teacher)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Teacher.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Academic_Year)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Academic_Year.Academic_yearName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Semester)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Semester.SemesterName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Faculity)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Faculity.Faculty_email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Department)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Department.Department_code)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Course)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Course.Course_code)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
    </dl>

    <div class="form-group">
        <form asp-action="Delete">
            <input type="hidden" asp-for="Course_teacher_id" />
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            <a asp-action="Index">Back to List</a>
        </form>
    </div>
</div>






   

SAS/Views/Course_teacher/Details.cshtml
@model SAS.Models.Course_teacher

@{
    ViewData["Title"] = "Details";
}


<div class="content-header" style="padding-left:250px; color:black;padding-bottom: 40px;padding-top: 10px;">
</div>

<div class="mainbody" style="padding-left:250px;">
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Teacher)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Teacher.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Academic_Year)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Academic_Year.Academic_yearName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Semester)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Semester.SemesterName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Faculity)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Faculity.Faculty_email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Department)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Department.Department_code)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Course)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Course.Course_code)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Course_teacher_id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>





    

SAS/Views/Course_teacher/Edit.cshtml
@model SAS.Models.Course_teacher

@{
    ViewData["Title"] = "Edit";
}


<div class="content-header" style="padding-left:250px; color:black;padding-bottom: 40px;padding-top: 10px;">
</div>

<div class="mainbody" style="padding-left:250px;">
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Course_teacher_id" />
            <div class="form-group">
                <label asp-for="Teacher_id" class="control-label"></label>
                <select asp-for="Teacher_id" class="form-control" asp-items="ViewBag.Teacher_id"></select>
                <span asp-validation-for="Teacher_id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Academic_y_id" class="control-label"></label>
                <select asp-for="Academic_y_id" class="form-control" asp-items="ViewBag.Academic_y_id"></select>
                <span asp-validation-for="Academic_y_id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Semester_id" class="control-label"></label>
                <select asp-for="Semester_id" class="form-control" asp-items="ViewBag.Semester_id"></select>
                <span asp-validation-for="Semester_id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Faculity_id" class="control-label"></label>
                <select asp-for="Faculity_id" class="form-control" asp-items="ViewBag.Faculity_id"></select>
                <span asp-validation-for="Faculity_id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Department_id" class="control-label"></label>
                <select asp-for="Department_id" class="form-control" asp-items="ViewBag.Department_id"></select>
                <span asp-validation-for="Department_id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Course_id" class="control-label"></label>
                <select asp-for="Course_id" class="form-control" asp-items="ViewBag.Course_id"></select>
                <span asp-validation-for="Course_id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <input asp-for="Status" class="form-control" />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
                    <a asp-action="Index">Back to List</a>
            </div>
        </form>
    </div>
</div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SAS/Views/Course_teacher/Index.cshtml
@model IEnumerable<SAS.Models.Course_teacher>

@{
    ViewData["Title"] = "Index";
}

<div class="content-header" style="padding-left:250px; color:black;padding-bottom: 40px;padding-top: 10px;">
    <a asp-action="Create" asp-controller="Course_teacher" class="btn btn-primary" style="float:right;"> Add New  </a>
</div>

<div class="mainbody" style="padding-left:250px;">
    <table id="example" class="display" style="width:100%">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Teacher)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Academic_Year)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Semester)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Faculity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Department)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Course)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                    @Html.DisplayFor(modelItem => item.Teacher.FullNameOfTeacher)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Academic_Year.Academic_yearName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Semester.SemesterName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Faculity.Faculty_name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Department.Department_name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Course.Course_name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Course_teacher_id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Course_teacher_id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Course_teacher_id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>
</div>