SAS/Models/Enrollment.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SAS.Models
{
    public class Enrollment
       
    {
        [Key]
        public int Enrollement_id { get; set; }

        [Required(ErrorMessage = "Student Name is required !")]
        [Display(Name = "Student Name")]
        public int Stud_id { get; set; }
        [ForeignKey("Stud_id")]
        public Student Student { get; set; }

        [Required(ErrorMessage = "Academic year is required !")]
        [Display(Name = "Academic year")]
        public int Academic_y_id { get; set; }
        [ForeignKey("Academic_y_id")]
        public Academic_Year Academic_Year { get; set; }

        [Required(ErrorMessage = "Course Name is required !")]
        [Display(Name = "Course Name")]
        public int Course_id { get; set; }
        [ForeignKey("Course_id")]
        public Course Course { get; set; }

        [Required(ErrorMessage = "Faculity Name is required !")]
        [Display(Name = "Faculity Name")]
        public int Faculity_id { get; set; }
        [ForeignKey("Faculity_id")]
        public Faculity Faculity { get; set; }

        [Required(ErrorMessage = "Semester is required !")]
        [Display(Name = "Semester")]
        public int Semester_id { get; set; }
        [ForeignKey("Semester_id")]
        public Semester Semester { get; set; }

        [Required(ErrorMessage = "Department Name is required !")]
        [Display(Name = "Department Name")]
        public int Department_id { get; set; }
        [ForeignKey("Department_id")]
        public Department Department { get; set; }

        [Required(ErrorMessage = "Enrollment date  is required !")]
        [Display(Name = "Enrollment date")]
        [DataType(DataType.Date)]
        public DateTime Enrollment_date { get; set; }
        [Required(ErrorMessage = "Status  is required !")]
        [Display(Name = "Status")]
        public string Status { get; set; }
        public virtual ICollection<Attendance> Attendance { get; set; }

    }
}

SAS/Controllers/EnrollmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SAS.Data;
using SAS.Models;

namespace SAS.Controllers
{
    public class EnrollmentsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public EnrollmentsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Enrollments
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Enrollment.Include(e => e.Academic_Year).Include(e => e.Course).Include(e => e.Department).Include(e => e.Faculity).Include(e => e.Semester).Include(e => e.Student);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Enrollments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Enrollment == null)
            {
                return NotFound();
            }

            var enrollment = await _context.Enrollment
                .Include(e => e.Academic_Year)
                .Include(e => e.Course)
                .Include(e => e.Department)
                .Include(e => e.Faculity)
                .Include(e => e.Semester)
                .Include(e => e.Student)
                .FirstOrDefaultAsync(m => m.Enrollement_id == id);
            if (enrollment == null)
            {
                return NotFound();
            }

            return View(enrollment);
        }

        // GET: Enrollments/Create
        public IActionResult Create()
        {
            ViewData["Academic_y_id"] = new SelectList(_context.Academic_Year, "Academic_y_id", "Academic_yearName");
            ViewData["Course_id"] = new SelectList(_context.Course, "Course_id", "Course_name");
            ViewData["Department_id"] = new SelectList(_context.Department, "Department_id", "Department_name");
            ViewData["Faculity_id"] = new SelectList(_context.Faculities, "Faculity_id", "Faculty_name");
            ViewData["Semester_id"] = new SelectList(_context.Semester, "Semester_id", "SemesterName");
            ViewData["Stud_id"] = new SelectList(_context.Student, "Stud_id", "FullName");
            return View();
        }

        // POST: Enrollments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Enrollement_id,Stud_id,Academic_y_id,Course_id,Faculity_id,Semester_id,Department_id,Enrollment_date,Status")] Enrollment enrollment)
        {
            if (!ModelState.IsValid)
            {
                _context.Add(enrollment);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Academic_y_id"] = new SelectList(_context.Academic_Year, "Academic_y_id", "Academic_yearName", enrollment.Academic_y_id);
            ViewData["Course_id"] = new SelectList(_context.Course, "Course_id", "Course_name", enrollment.Course_id);
            ViewData["Department_id"] = new SelectList(_context.Department, "Department_id", "Department_name", enrollment.Department_id);
            ViewData["Faculity_id"] = new SelectList(_context.Faculities, "Faculity_id", "Faculty_name", enrollment.Faculity_id);
            ViewData["Semester_id"] = new SelectList(_context.Semester, "Semester_id", "SemesterName", enrollment.Semester_id);
            ViewData["Stud_id"] = new SelectList(_context.Student, "Stud_id", "FullName", enrollment.Stud_id);
            return View(enrollment);
        }

        // GET: Enrollments/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Enrollment == null)
            {
                return NotFound();
            }

            var enrollment = await _context.Enrollment.FindAsync(id);
            if (enrollment == null)
            {
                return NotFound();
            }
            ViewData["Academic_y_id"] = new SelectList(_context.Academic_Year, "Academic_y_id", "Academic_yearName", enrollment.Academic_y_id);
            ViewData["Course_id"] = new SelectList(_context.Course, "Course_id", "Course_name", enrollment.Course_id);
            ViewData["Department_id"] = new SelectList(_context.Department, "Department_id", "Department_name", enrollment.Department_id);
            ViewData["Faculity_id"] = new SelectList(_context.Faculities, "Faculity_id", "Faculty_name", enrollment.Faculity_id);
            ViewData["Semester_id"] = new SelectList(_context.Semester, "Semester_id", "SemesterName", enrollment.Semester_id);
            ViewData["Stud_id"] = new SelectList(_context.Student, "Stud_id", "FullName", enrollment.Stud_id);
            return View(enrollment);
        }

        // POST: Enrollments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Enrollement_id,Stud_id,Academic_y_id,Course_id,Faculity_id,Semester_id,Department_id,Enrollment_date,Status")] Enrollment enrollment)
        {
            if (id != enrollment.Enrollement_id)
            {
                return NotFound();
            }

            if (!ModelState.IsValid)
            {
                try
                {
                    _context.Update(enrollment);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EnrollmentExists(enrollment.Enrollement_id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Academic_y_id"] = new SelectList(_context.Academic_Year, "Academic_y_id", "Academic_yearName", enrollment.Academic_y_id);
            ViewData["Course_id"] = new SelectList(_context.Course, "Course_id", "Course_name", enrollment.Course_id);
            ViewData["Department_id"] = new SelectList(_context.Department, "Department_id", "Department_name", enrollment.Department_id);
            ViewData["Faculity_id"] = new SelectList(_context.Faculities, "Faculity_id", "Faculty_name", enrollment.Faculity_id);
            ViewData["Semester_id"] = new SelectList(_context.Semester, "Semester_id", "SemesterName", enrollment.Semester_id);
            ViewData["Stud_id"] = new SelectList(_context.Student, "Stud_id", "FullName", enrollment.Stud_id);
            return View(enrollment);
        }

        // GET: Enrollments/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Enrollment == null)
            {
                return NotFound();
            }

            var enrollment = await _context.Enrollment
                .Include(e => e.Academic_Year)
                .Include(e => e.Course)
                .Include(e => e.Department)
                .Include(e => e.Faculity)
                .Include(e => e.Semester)
                .Include(e => e.Student)
                .FirstOrDefaultAsync(m => m.Enrollement_id == id);
            if (enrollment == null)
            {
                return NotFound();
            }

            return View(enrollment);
        }

        // POST: Enrollments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Enrollment == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Enrollment'  is null.");
            }
            var enrollment = await _context.Enrollment.FindAsync(id);
            if (enrollment != null)
            {
                _context.Enrollment.Remove(enrollment);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EnrollmentExists(int id)
        {
          return (_context.Enrollment?.Any(e => e.Enrollement_id == id)).GetValueOrDefault();
        }
    }
}

SAS/Views/Enrollments/Create.cshtml
@model SAS.Models.Enrollment

@{
    ViewData["Title"] = "Create";
}

<div class="content-header" style="padding-left:250px; color:black;padding-bottom: 40px;padding-top: 10px;">
</div>

<div class="mainbody" style="padding-left:250px;">
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Stud_id" class="control-label"></label>
                <select asp-for="Stud_id" class ="form-control" asp-items="ViewBag.Stud_id"></select>
            </div>
            <div class="form-group">
                <label asp-for="Academic_y_id" class="control-label"></label>
                <select asp-for="Academic_y_id" class ="form-control" asp-items="ViewBag.Academic_y_id"></select>
            </div>
            <div class="form-group">
                <label asp-for="Course_id" class="control-label"></label>
                <select asp-for="Course_id" class ="form-control" asp-items="ViewBag.Course_id"></select>
            </div>
            <div class="form-group">
                <label asp-for="Faculity_id" class="control-label"></label>
                <select asp-for="Faculity_id" class ="form-control" asp-items="ViewBag.Faculity_id"></select>
            </div>
            <div class="form-group">
                <label asp-for="Semester_id" class="control-label"></label>
                <select asp-for="Semester_id" class ="form-control" asp-items="ViewBag.Semester_id"></select>
            </div>
            <div class="form-group">
                <label asp-for="Department_id" class="control-label"></label>
                <select asp-for="Department_id" class ="form-control" asp-items="ViewBag.Department_id"></select>
            </div>
            <div class="form-group">
                <label asp-for="Enrollment_date" class="control-label"></label>
                <input asp-for="Enrollment_date" class="form-control" />
                <span asp-validation-for="Enrollment_date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <input asp-for="Status" class="form-control" />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
                    <a asp-action="Index">Back to List</a>
            </div>
        </form>
    </div>
</div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SAS/Views/Enrollments/Delete.cshtml
@model SAS.Models.Enrollment

@{
    ViewData["Title"] = "Delete";
}

<div class="content-header" style="padding-left:250px; color:black;padding-bottom: 40px;padding-top: 10px;">
    <h3>Are you sure you want to delete this?</h3>
</div>

<div class="mainbody" style="padding-left:250px;">
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Student)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Student.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Academic_Year)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Academic_Year.Academic_yearName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Course)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Course.Course_code)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Faculity)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Faculity.Faculty_email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Semester)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Semester.SemesterName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Department)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Department.Department_code)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Enrollment_date)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Enrollment_date)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
    </dl>

    <div class="form-group">
        <form asp-action="Delete">
            <input type="hidden" asp-for="Enrollement_id" />
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            <a asp-action="Index">Back to List</a>
        </form>
    </div>
</div>




   

SAS/Views/Enrollments/Details.cshtml
@model SAS.Models.Enrollment

@{
    ViewData["Title"] = "Details";
}

<div class="content-header" style="padding-left:250px; color:black;padding-bottom: 40px;padding-top: 10px;">
</div>

<div class="mainbody" style="padding-left:250px;">
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Student)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Student.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Academic_Year)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Academic_Year.Academic_yearName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Course)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Course.Course_code)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Faculity)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Faculity.Faculty_email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Semester)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Semester.SemesterName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Department)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Department.Department_code)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Enrollment_date)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Enrollment_date)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Enrollement_id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>






    

SAS/Views/Enrollments/Edit.cshtml
@model SAS.Models.Enrollment

@{
    ViewData["Title"] = "Edit";
}

<div class="content-header" style="padding-left:250px; color:black;padding-bottom: 40px;padding-top: 10px;">
</div>

<div class="mainbody" style="padding-left:250px;">
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Enrollement_id" />
            <div class="form-group">
                <label asp-for="Stud_id" class="control-label"></label>
                <select asp-for="Stud_id" class="form-control" asp-items="ViewBag.Stud_id"></select>
                <span asp-validation-for="Stud_id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Academic_y_id" class="control-label"></label>
                <select asp-for="Academic_y_id" class="form-control" asp-items="ViewBag.Academic_y_id"></select>
                <span asp-validation-for="Academic_y_id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Course_id" class="control-label"></label>
                <select asp-for="Course_id" class="form-control" asp-items="ViewBag.Course_id"></select>
                <span asp-validation-for="Course_id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Faculity_id" class="control-label"></label>
                <select asp-for="Faculity_id" class="form-control" asp-items="ViewBag.Faculity_id"></select>
                <span asp-validation-for="Faculity_id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Semester_id" class="control-label"></label>
                <select asp-for="Semester_id" class="form-control" asp-items="ViewBag.Semester_id"></select>
                <span asp-validation-for="Semester_id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Department_id" class="control-label"></label>
                <select asp-for="Department_id" class="form-control" asp-items="ViewBag.Department_id"></select>
                <span asp-validation-for="Department_id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Enrollment_date" class="control-label"></label>
                <input asp-for="Enrollment_date" class="form-control" />
                <span asp-validation-for="Enrollment_date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <input asp-for="Status" class="form-control" />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
                    <a asp-action="Index">Back to List</a>
            </div>
        </form>
    </div>
</div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SAS/Views/Enrollments/Index.cshtml
@model IEnumerable<SAS.Models.Enrollment>

@{
    ViewData["Title"] = "Index";
}
<div class="content-header" style="padding-left:250px; color:black;padding-bottom: 40px;padding-top: 10px;">
    <a asp-action="Create" asp-controller="Enrollments" class="btn btn-primary" style="float:right;"> Add New  </a>
</div>

<div class="mainbody" style="padding-left:250px;">
    <table id="example" class="display" style="width:100%">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Student)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Academic_Year)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Course)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Faculity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Semester)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Department)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Enrollment_date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Student.FullName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Academic_Year.Academic_yearName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Course.Course_name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Faculity.Faculty_name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Semester.SemesterName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Department.Department_name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Enrollment_date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Enrollement_id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Enrollement_id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Enrollement_id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>
</div>