SAS/Models/Department_course.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SAS.Models
{
    public class Department_course
    {
        [Key]

        public int Dept_course_id { get; set; }

        [Required(ErrorMessage = "Department Name is required !")]
        [Display(Name = "Department Name")]
        public int Department_id { get; set; }
        [ForeignKey("Department_id")]
        public Department Department { get; set; }

        [Required(ErrorMessage = "Course Name is required !")]
        [Display(Name = "Course Name")]
        public int Course_id { get; set; }
        [ForeignKey("Course_id")]
        public Course Course { get; set; }

        [Required(ErrorMessage = " Year is required !")]
        [Display(Name = "Year")]
        public int Year_id { get; set; }
        [ForeignKey("Year_id")]

        public Year Year { get; set; }

        [Required(ErrorMessage = "Semester is required !")]
        [Display(Name = "Semester")]
        public int Semester_id { get; set; }
        [ForeignKey("Semester_id")]

        public Semester Semester { get; set; }

        [Required(ErrorMessage = "Status is required !")]
        [Display(Name = "Status")]
        public string Status { get; set; }
    }
}

SAS/Controllers/Department_courseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SAS.Data;
using SAS.Models;

namespace SAS.Controllers
{
    public class Department_courseController : Controller
    {
        private readonly ApplicationDbContext _context;

        public Department_courseController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Department_course
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Department_course.Include(d => d.Course).Include(d => d.Department).Include(d => d.Semester).Include(d => d.Year);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Department_course/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Department_course == null)
            {
                return NotFound();
            }

            var department_course = await _context.Department_course
                .Include(d => d.Course)
                .Include(d => d.Department)
                .Include(d => d.Semester)
                .Include(d => d.Year)
                .FirstOrDefaultAsync(m => m.Dept_course_id == id);
            if (department_course == null)
            {
                return NotFound();
            }

            return View(department_course);
        }

        // GET: Department_course/Create
        public IActionResult Create()
        {
            ViewData["Course_id"] = new SelectList(_context.Course, "Course_id", "Course_name");
            ViewData["Department_id"] = new SelectList(_context.Department, "Department_id", "Department_name");
            ViewData["Semester_id"] = new SelectList(_context.Semester, "Semester_id", "SemesterName");
            ViewData["Year_id"] = new SelectList(_context.Year, "Year_id", "yearName");
            return View();
        }

        // POST: Department_course/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Dept_course_id,Department_id,Course_id,Year_id,Semester_id,Status")] Department_course department_course)
        {
            if (!ModelState.IsValid)
            {
                _context.Add(department_course);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Course_id"] = new SelectList(_context.Course, "Course_id", "Course_name", department_course.Course_id);
            ViewData["Department_id"] = new SelectList(_context.Department, "Department_id", "Department_name", department_course.Department_id);
            ViewData["Semester_id"] = new SelectList(_context.Semester, "Semester_id", "SemesterName", department_course.Semester_id);
            ViewData["Year_id"] = new SelectList(_context.Year, "Year_id", "yearName", department_course.Year_id);
            return View(department_course);
        }

        // GET: Department_course/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Department_course == null)
            {
                return NotFound();
            }

            var department_course = await _context.Department_course.FindAsync(id);
            if (department_course == null)
            {
                return NotFound();
            }
            ViewData["Course_id"] = new SelectList(_context.Course, "Course_id", "Course_name", department_course.Course_id);
            ViewData["Department_id"] = new SelectList(_context.Department, "Department_id", "Department_name", department_course.Department_id);
            ViewData["Semester_id"] = new SelectList(_context.Semester, "Semester_id", "SemesterName", department_course.Semester_id);
            ViewData["Year_id"] = new SelectList(_context.Year, "Year_id", "yearName", department_course.Year_id);
            return View(department_course);
        }

        // POST: Department_course/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Dept_course_id,Department_id,Course_id,Year_id,Semester_id,Status")] Department_course department_course)
        {
            if (id != department_course.Dept_course_id)
            {
                return NotFound();
            }

            if (!ModelState.IsValid)
            {
                try
                {
                    _context.Update(department_course);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!Department_courseExists(department_course.Dept_course_id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Course_id"] = new SelectList(_context.Course, "Course_id", "Course_name", department_course.Course_id);
            ViewData["Department_id"] = new SelectList(_context.Department, "Department_id", "Department_name", department_course.Department_id);
            ViewData["Semester_id"] = new SelectList(_context.Semester, "Semester_id", "SemesterName", department_course.Semester_id);
            ViewData["Year_id"] = new SelectList(_context.Year, "Year_id", "yearName", department_course.Year_id);
            return View(department_course);
        }

        // GET: Department_course/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Department_course == null)
            {
                return NotFound();
            }

            var department_course = await _context.Department_course
                .Include(d => d.Course)
                .Include(d => d.Department)
                .Include(d => d.Semester)
                .Include(d => d.Year)
                .FirstOrDefaultAsync(m => m.Dept_course_id == id);
            if (department_course == null)
            {
                return NotFound();
            }

            return View(department_course);
        }

        // POST: Department_course/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Department_course == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Department_course'  is null.");
            }
            var department_course = await _context.Department_course.FindAsync(id);
            if (department_course != null)
            {
                _context.Department_course.Remove(department_course);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool Department_courseExists(int id)
        {
          return (_context.Department_course?.Any(e => e.Dept_course_id == id)).GetValueOrDefault();
        }
    }
}

SAS/Views/Department_course/Create.cshtml
@model SAS.Models.Department_course

@{
    ViewData["Title"] = "Create";
}

<div class="content-header" style="padding-left:250px; color:black;padding-bottom: 40px;padding-top: 10px;">
</div>

<div class="mainbody" style="padding-left:250px;">
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Department_id" class="control-label"></label>
                <select asp-for="Department_id" class ="form-control" asp-items="ViewBag.Department_id"></select>
            </div>
            <div class="form-group">
                <label asp-for="Course_id" class="control-label"></label>
                <select asp-for="Course_id" class ="form-control" asp-items="ViewBag.Course_id"></select>
            </div>
            <div class="form-group">
                <label asp-for="Year_id" class="control-label"></label>
                <select asp-for="Year_id" class ="form-control" asp-items="ViewBag.Year_id"></select>
            </div>
            <div class="form-group">
                <label asp-for="Semester_id" class="control-label"></label>
                <select asp-for="Semester_id" class ="form-control" asp-items="ViewBag.Semester_id"></select>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <input asp-for="Status" class="form-control" />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
                    <a asp-action="Index">Back to List</a>
            </div>
        </form>
    </div>
</div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SAS/Views/Department_course/Delete.cshtml
@model SAS.Models.Department_course

@{
    ViewData["Title"] = "Delete";
}

<div class="content-header" style="padding-left:250px; color:black;padding-bottom: 40px;padding-top: 10px;">
    <h3>Are you sure you want to delete this?</h3>
</div>

<div class="mainbody" style="padding-left:250px;">

    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Department)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Department.Department_code)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Course)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Course.Course_code)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Year)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Year.yearName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Semester)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Semester.SemesterName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
    </dl>
    <div class="form-group">
        <form asp-action="Delete">
            <input type="hidden" asp-for="Dept_course_id" />
            <input type="submit" value="Delete" class="btn btn-danger" /> 
            <a asp-action="Index">Back to List</a>
        </form>
    </div>
</div>

SAS/Views/Department_course/Details.cshtml
@model SAS.Models.Department_course

@{
    ViewData["Title"] = "Details";
}


<div class="content-header" style="padding-left:250px; color:black;padding-bottom: 40px;padding-top: 10px;">
</div>

<div class="mainbody" style="padding-left:250px;">
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Department)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Department.Department_code)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Course)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Course.Course_code)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Year)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Year.yearName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Semester)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Semester.SemesterName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Dept_course_id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>




   

SAS/Views/Department_course/Edit.cshtml
@model SAS.Models.Department_course

@{
    ViewData["Title"] = "Edit";
}

<div class="content-header" style="padding-left:250px; color:black;padding-bottom: 40px;padding-top: 10px;">
</div>

<div class="mainbody" style="padding-left:250px;">
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Dept_course_id" />
            <div class="form-group">
                <label asp-for="Department_id" class="control-label"></label>
                <select asp-for="Department_id" class="form-control" asp-items="ViewBag.Department_id"></select>
                <span asp-validation-for="Department_id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Course_id" class="control-label"></label>
                <select asp-for="Course_id" class="form-control" asp-items="ViewBag.Course_id"></select>
                <span asp-validation-for="Course_id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Year_id" class="control-label"></label>
                <select asp-for="Year_id" class="form-control" asp-items="ViewBag.Year_id"></select>
                <span asp-validation-for="Year_id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Semester_id" class="control-label"></label>
                <select asp-for="Semester_id" class="form-control" asp-items="ViewBag.Semester_id"></select>
                <span asp-validation-for="Semester_id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <input asp-for="Status" class="form-control" />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
                    <a asp-action="Index">Back to List</a>
            </div>
        </form>
    </div>
</div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SAS/Views/Department_course/Index.cshtml
@model IEnumerable<SAS.Models.Department_course>

@{
    ViewData["Title"] = "Index";
}

<div class="content-header" style="padding-left:250px; color:black;padding-bottom: 40px;padding-top: 10px;">
    <a asp-action="Create" asp-controller="Department_course" class="btn btn-primary" style="float:right;"> Add New  </a>
</div>

<div class="mainbody" style="padding-left:250px;">
    <table id="example" class="display" style="width:100%">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Department)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Course)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Year)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Semester)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Department.Department_name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Course.Course_name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Year.yearName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Semester.SemesterName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Dept_course_id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Dept_course_id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Dept_course_id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>
</div>